name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: permission bypass
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/Asad657/ssrf-test/actions/secrets/TEST_SECRET" | python3 -m json.tool | head -10
          curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/Asad657/Assuhere/actions/secrets" | python3 -m json.tool | head -10
          curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/Asad657/Assuhere/contents/" | python3 -m json.tool | head -10
