name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cross repo
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Asad657/ssrf-test/actions/secrets" | python3 -m json.tool | head -10
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/github/actions/secrets" | python3 -m json.tool | head -10
