name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: network scan
        run: |
          curl -s -m 2 http://10.0.0.1/ || true
          curl -s -m 2 http://172.16.0.1/ || true
          curl -s -m 2 http://192.168.0.1/ || true
          curl -s -m 2 http://168.63.129.16/ || true
          ip route || true
          cat /etc/hosts || true
